version: '3'
services:
  xb:
    image: ghcr.io/cedar2025/xboard:latest
    ports:
       - "7002:7001"
    volumes:
      - ./.env:/www/.env
      - ./.docker/.data/:/www/.docker/.data/
      # - ./config/v2board.php:/www/config/v2board.php
    environment:
      - docker=true #用于给安装脚本判断是否为docker环境
    restart: always
    networks:
      xb-net:
        ipv4_address: 172.20.0.pp

networks:
  xb-net:
    external: true
    name: mynet