version: '3.0'

services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf: /etc/nginx/conf.d/
      - ./log:/var/log/nginx
      - ./www:/usr/share/nginx/html
      - ./cert:/etc/nginx/cert
    networks:
      nginx-net:
         ipv4_address: 172.20.0.220
networks:
  nginx-net:
    external: true
    name: mynet